### ISSUE TITLE
Occasional freezing

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#102]
This happened several times already, after a while in free play the game randomly freezes in an infinite loop. It happens both during active gameplay and in background. Don't know the exact way to replicate that, try to leave the game on for a while in the background.

**Comment by Vadru93** [comment]
I never had this issue, is it only in single player?

**Comment by DCxDemo** [comment]
I guess any mode. Here's the example of it happening basically on the ground, no inputs, almost 9 minutes in the run, smallest was about 4 minutes.
![342789](https://user-images.githubusercontent.com/13422696/107776617-77368000-6d4a-11eb-9ade-b84cfcaf9314.png)

**Comment by DCxDemo** [comment]
still freezes.

**Comment by Vadru93** [comment]
Yeah I noticed it’s still producing wrong timers sometimes,  not sure why that is...

The problem is that some stuff only use the low part of the queryperformancecounter, but to my understanding it should not refresh that often when you substract the starting time, but still sometimes it does and produces negative time elapsed..

Guess I need to look into the exact math of the old timer or simply use the old timer, or only use GetTickCount timer with 49 days reset. But think that one might reduce resolution slightly.
