### ISSUE TITLE
Windowed menu option is not synced with actual windowed state

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#116]
Steps to reproduce:
- enter graphics menu in fullscreen
- press alt+enter
- menu still shows off
- press right
- menu changes to on and nothing happens
- change once again and it switches to fullscreen

**Comment by Vadru93** [comment]
That's actually on purpose, the alt + enter functionality is only to be able to change between windowed mode and fullscreen on the fly. While the setting is if the game should start in windowed or not.

Since I could not make the toggle to work if game is launched in fullscreen mode you will need the option on to be able to toggle.

And let's say you want to toggle between fullscreen and windowed instead of alt tabing for example, and you exit the game in fullscreen mode then next time you launch the game it would launch in fullscreen if alt + enter would change the settings.

The ultimate fix for this is to make it so that you can toggle windowed even if game is launched in fullscreen.
Until then I think it should stay how it is.

**Comment by DCxDemo** [comment]
can you always launch it in a window and then toggle to fullscreen as soon as possible?
