### ISSUE TITLE
Sound effect may randomly play at a very high volume

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#43]
This is easy to spot while breaking multiple glasses consecutively (college, vancouver), once in a while there will be a very loud sound. Could be PlaySound bug or some deeper mixing bug in mss32.

**Comment by Vadru93** [comment]
Does this happen in original levels aswell?

**Comment by DCxDemo** [comment]
in cruise ship if you grind the top rail by launching from the ramp towards the tail part of the ship, the very last glass is constantly twice louder i think. should probably actually check how many times triggerscript or playsound is called. it could be a mixing issue indeed. maybe can check how mss32 handles channel mixing, maybe it supports different mixing modes.

in theory can also add some kind of sound queue and more glass breaking sounds, so it doesn't play same sound simultaneously, will add some variety as well.

**Comment by Vadru93** [comment]
It seems this issue is actually because TriggerScript is called multiple times.
Probably should add a timer to make sure same trigger is not triggered within 0.5 sec, not sure if anythinh would get broken by this?

**Comment by DCxDemo** [comment]
Maybe should reverse the logic a bit, why exactly does it happen? is it like kill command is queued and actually happens a few frames later, so there can be multiple collision frames that trigger the script before the object is actually killed? are there any marks that the object is killed? maybe it skips the check for some reason?

if trigger is intended to only be triggered once, then yes, but i guess you can use it in a "while skater in area, trigger constantly" way and that will definitely break. like if you don't kill the object intentionally.

**Comment by Vadru93** [comment]
The scripts are executed in 1 thread and the game logic in another thread. So if the script thread falls behind I guess multiply triggers can happen before game logic know the object is flaged to get killed.

Optimal would be to try and time/optimize these threads better to not fail like this. However easiest is to just store last triggerscript and last trigger frame count and if new triggernode == lasr triggernode and framecount - last framecount < 30 don't trigger script. Or maybe find the where the node flags are and make it flaged as killed at the same time as the super sector flag. 

For now I can't think of anything that would be broken by this, since actuallly trigger should only happen when you skate through the object and maybe this bug is actually with physics update code or something? Maybe if framerate is running low the physics don't have time to update before new frame is started. Since actually it should be impossible to hit so many triggers in so few frames.
Probably should try to add some debut print like each time a triggernode happens(from where? Skaterpos? Old skaterpos? Framecount, etc)

**Comment by Vadru93** [comment]
Maybe fixed in 00264922743d4832384abb1393ebd983954ada36
