### ISSUE TITLE
Attempting to open a movie crashes the game

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#76]
Attempting to open a movie in movies menu crashes the game as reported in #74
Intro movies do not crash though.

**Comment by Vadru93** [comment]
It seems that controller config, video crash and probably also go_back bug and right click mouse button all boils down to stack being trashed somehow. At first I thought maybe it's because of levelmod settings menu, but after removing CreateAndAttach menu it's still there, which is both fortunet and unfortunet. it would be really nice to know when these crashes started to happen so I can fix the stack once and for all.

**Comment by DCxDemo** [comment]
This one is related to stutter fix.
off - movie works
exact - movie crashes after a few seconds
hybrid - crashes instantly
sleep - crashes instantly

Also, in off mode, nothing actually works, skater freezes in starting anim, run doesn't start etc.

**Comment by Vadru93** [comment]
Yeah I noticed off is kinda trashed and it seems the stack is slightly trashed in all of them which is intresting. So I will look into fixing this, which will probably fix many of the current random bugs we have.
