### ISSUE TITLE
Share levelmod settings online

### ISSUE THREAD

**Issue by DCxDemo** [Vadru93/LevelMod#8]
Gotta come with a way to force server settings online, so everyone on the host is even.
Can somehow store a separate settings set received from host and restore local settings in main menu.

**Comment by Vadru93** [comment]
I was thinking we can add a override flag, for example
{ name = "LM_Control_bAllowSpine" Value = 0 override = LM_HostOptions_bAllowSpine }
And LM_HostOptions should be a seperate menu because host should be able to allow spine even if spine is not on for him.
Then whenever an option is changed by host he can send data to clients, before I figure out how to fix this in an easy way could just use chat messages and send something like /COMMAND OptionsChanged
And if chatmessage contains /COMMAND OptionsChanged client will listen for packets.
The ideal would be to dissamble the send data functions, but right now it's probably not prio 1 since we should try to focus to fix levels so we can finally make a new full build release.
